---
title       : Biomimetic set up for chemosensor-based machine olfaction
title1      : Biomimetic set up for
title2      : chemosensor-based
title3      : machine olfaction
subtitle    : PhD thesis defense presentation
author      : Andrey Ziyatdinov
aspirant    : Andrey Ziyatdinov
adviser     : Alexandre Perera i Lluna
dept        : Departament ESAII, Universitat Politècnica de Catalunya (UPC)
dat         : 4 December, 2014
license     : by-nc-sa
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js # {highlight.js, prettify, highlight}
hitheme     : tomorrow       # solarized_light
widgets     : mathjax          # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

<link rel="stylesheet" href="assets/css/thesis.css">


```{r setup, echo = FALSE, message = FALSE, cache = FALSE}
# set global chunk options
opts_chunk$set(fig.path = 'figure/', cache.path = 'cache/', echo = FALSE, cache = FALSE, 
  tidy = FALSE, 
  fig.width = 9, fig.height = 4.5, dev = 'png',
  warning = FALSE, message = FALSE)
# upload images automatically? (identity/imgur_upload)
opts_knit$set(upload.fun = identity)
```

```{r knitcitations, eval = FALSE}
library(knitcitations)
bib <- read.bibtex("mendeley.bib")
```

## About this presentation

--- .segue .quote bg:#99CC99

## Results

--- .fill bg:url(images/sand.jpg) no-repeat

## Drift

<footer class="source white">https://www.flickr.com/photos/michaelkeith/6905715219/</footer>

